import { CardData } from "./lib/types";

export const initialData: Array<CardData> = [
    { content: "My code doesn't work", marked: false },
    { content: "My build is failing", marked: false },
    { content: "Hey ____, do you have a second?", marked: false },
    { content: "My tests are failing", marked: false },
    { content: "Getting merge conflicts.", marked: false },
    { content: "Why should we rebase?", marked: false },
    { content: "Only one story point?", marked: false },
    { content: "Let's grab a quick coffee", marked: false },
    { content: "Why do we use typescript here?", marked: false },
    { content: "Do we need tests here?", marked: false },
    { content: "The API doesn't return response", marked: false },
    { content: "Can you explain this?", marked: false },
    { content: "Pair-Programming Bingo", marked: true },
    { content: "Is my code clean?", marked: false },
    { content: "Cannot update the state", marked: false },
    { content: "Could you repeat that?", marked: false },
    { content: "Let's write down the problem", marked: false },
    { content: "I got this from here", marked: false },
    { content: "Did you understand this?", marked: false },
    { content: "What is JSDoc?", marked: false },
    { content: "Could be done this way", marked: false },
    { content: "Can we refactor this?", marked: false },
    { content: "What's the time complexity", marked: false },
    { content: "Line ___ doesn't exist", marked: false },
    { content: "There's the problem.", marked: false },
  ];